import random;
print(random.choice([
  'addition_simple.py',
  'circuit_simple.py',
  'circuit_simple_2.py',
  'complex.py',
  'correlation_coefficient.py',
  'division_simple.py',
  'input_integer.py',
  'input_single.py',
  'modulo_simple.py',
  'multiplication_simple.py',
  'nada_fn_composition.py',
  'nada_fn_simple.py',
  'reduce_simple.py',
  'reuse.py',
  'reuse_flipped1.py',
  'reuse_flipped2.py',
  'reuse_simple_1.py',
  'reuse_simple_2.py',
  'reuse_simple_sub.py',
  'simple.py',
  'simple_literals.py',
  'simple_public_variables.py',
  'simple_public_variables_only.py',
  'simple_sub.py',
  'single_addition.py',
  'subtraction_simple.py',
  'subtraction_simple_neg.py',
  'tiny_secret_addition.py',
  'tiny_secret_addition_complete.py',
  # 'examples_and_tutorials/core_concept_store_and_retrieve_secrets/store_and_retrieve_blob.py',
  # 'examples_and_tutorials/core_concept_store_and_retrieve_secrets/store_and_retrieve_integer.py',
  # 'examples_and_tutorials/core_concept_multi_party_compute/01_store_secret_party1.py',
  # 'examples_and_tutorials/core_concept_multi_party_compute/02_store_secret_party_n.py',
  # 'examples_and_tutorials/core_concept_multi_party_compute/03_multi_party_compute.py'
  ]))